sudo: required
dist: xenial
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
      node_js: "10"
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run build:linux
    else
      npm run build:mac
    fi
after_success: 
  - cd build
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ls -l
    else
      ls -l
    fi
branches:
  only:
  - master