matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      sudo: required
      dist: bionic
      language: node_js
      node_js: "12"
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - libopenjp2-tools
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run build:linux
    else
      npm run build:mac
    fi
after_success: 
  - cd build
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cp Mius-i386.AppImage mius-$TRAVIS_OS_NAME-i386.AppImage
      cp Mius-i386.AppImage ../mius-$TRAVIS_OS_NAME-i386.AppImage
      cp Mius-x86_64.AppImage mius-$TRAVIS_OS_NAME-x86_64.AppImage
      cp Mius-x86_64.AppImage ../mius-$TRAVIS_OS_NAME-x86_64.AppImage
    else
      cp Mius.dmg mius-$TRAVIS_OS_NAME.dmg
      cp Mius.dmg ../mius-$TRAVIS_OS_NAME.dmg
    fi
deploy:
  provider: releases
  file:
  - mius-$TRAVIS_OS_NAME-i386.AppImage
  - mius-$TRAVIS_OS_NAME-x86_64.AppImage
  - mius-$TRAVIS_OS_NAME.dmg
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
  api-key: $Millux