matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      language: node_js
      node_js: "12"
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - libopenjp2-tools
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm run build:linux
    else
      npm run build:mac
    fi
after_success: 
  - cd build
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ls -l
    else
      ls -l
    fi
branches:
  only:
  - master