matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      language: node_js
      node_js: "10"
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install --no-install-recommends -y libopenjp2-tools
      npm install
      npm run build:linux
    else
      npm run build:mac
    fi
after_success: 
  - cd build
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ls -l
    else
      ls -l
    fi
branches:
  only:
  - master