version: 1.0.{build}

image: Visual Studio 2017
platform:
  - x64
environment:
  GH_TOKEN:
    secure: QApTMXYx9yadrrlsoagOyHV1ZSJtCa60hCqKlkqB9OymwNuBB1m0cVdTllr+uYMd

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build:win

after_build:
  - cd build
  - cp -fr ./Mius-Setup.exe ../mius-win-setup.exe
  - cd ..

artifacts:
  - path: mius-win-setup.exe
    name: mius-win-setup

deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: QApTMXYx9yadrrlsoagOyHV1ZSJtCa60hCqKlkqB9OymwNuBB1m0cVdTllr+uYMd
  on:
    APPVEYOR_REPO_TAG: true

test: off